"use client";

import { useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AlertTriangle, BadgeCheck, BookOpenCheck, BriefcaseBusiness, Building2, ChevronRight, CircleHelp, Cloud, FileCheck2, Fingerprint, Gauge, GraduationCap, LayoutDashboard, Menu, Network, Search, Shield, ShieldAlert, ShieldCheck, Siren, Target, Users, X } from "lucide-react";
import { controls, dataNotice, evidence, evidenceReadiness, kpis, managementActions, maturityDomains, procurement, progressTrend, projects, risks, roadmap, samaSummary, solutions, vendors } from "@/data/dashboard";
import { SectionId, Status } from "@/types";

const nav = [["overview","Command Center",LayoutDashboard],["sama","SAMA CSF",ShieldCheck],["risks","Risk Register",ShieldAlert],["stack","Security Stack",Fingerprint],["infrastructure","Infrastructure",Network],["third-parties","Third Parties",Building2],["resilience","Resilience",Siren],["people","People & Awareness",Users],["roadmap","Roadmap",Target],["data","Data & Updates",FileCheck2]] as const;
const statusClass: Record<string,string> = {"Completed":"green","Operational":"green","In Progress":"blue","Planned":"slate","Pending Approval":"amber","Blocked":"red","On Hold":"purple","Overdue":"red","Gap":"orange","Needs Verification":"gray","Proposed":"slate"};
function Badge({ status }: { status: Status | string }) { return <span className={`badge ${statusClass[status] || "gray"}`}><span />{status}</span>; }
function EmptyValue({ value }: { value: string | number | null }) { return <>{value === null ? <span className="muted">Not entered</span> : value}</>; }
function Panel({ title, eyebrow, children, action }: { title:string; eyebrow?:string; children:React.ReactNode; action?:React.ReactNode }) { return <section className="panel"><div className="panel-head"><div>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2></div>{action}</div>{children}</section>; }
function Donut({ data }: { data:{name:string;value:number}[] }) { const colors=["#19c3a2","#4f88ff","#2a3345"]; return <div className="chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" innerRadius={56} outerRadius={78} paddingAngle={3}>{data.map((_,i)=><Cell key={i} fill={colors[i]} />)}</Pie><Tooltip contentStyle={{background:"#101827",border:"1px solid #25334a",borderRadius:12}} /></PieChart></ResponsiveContainer></div>; }
function PageTitle({eyebrow,title,subtitle,badge}:{eyebrow:string;title:string;subtitle:string;badge:string}) { return <div className="page-title"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{subtitle}</p></div><div className="page-badge">{badge}</div></div> }
function DataTable({columns,rows}:{columns:string[];rows:React.ReactNode[][]}) { return <div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div> }

function Overview({ onGo }: { onGo:(s:SectionId)=>void }) { return <>
  <div className="page-title"><div><p className="eyebrow">Executive posture • 20 Sep 2026</p><h1>Cybersecurity Command Center</h1><p>One decision-ready view across governance, operations, resilience and delivery.</p></div><div className="target-chip"><Target size={18}/><span>Primary target</span><strong>SAMA ML3</strong></div></div>
  <div className="notice"><CircleHelp size={18}/><span>{dataNotice}</span></div>
  <div className="kpi-grid">{kpis.map((k)=><button className={`kpi ${k.tone}`} key={k.label} onClick={()=>onGo(k.section)}><p>{k.label}</p><strong>{k.primary}</strong><span>{k.secondary}</span><ChevronRight size={17}/></button>)}</div>
  <div className="two-col"><Panel title="Management attention required" eyebrow="Decision queue" action={<span className="count">{managementActions.length} items</span>}><div className="attention-list">{managementActions.map((a)=><div className="attention" key={a.issue}><span className={`severity ${a.status==="On Hold"?"purple":a.status==="Pending Approval"?"amber":"blue"}`}/><div><strong>{a.issue}</strong><p>{a.impact}</p><span>{a.decision}</span></div><div className="attention-meta"><Badge status={a.status}/><small>{a.owner}</small></div></div>)}</div></Panel>
  <Panel title="SAMA CSF direction" eyebrow="Maturity snapshot"><div className="maturity-hero"><div><span>Current maturity</span><strong>Needs<br/>Verification</strong></div><div className="ml-orbit"><span>ML</span><b>3</b><small>Target</small></div></div><div className="domain-mini">{maturityDomains.map(d=><div key={d.name}><span>{d.name}</span><div><i style={{width:`${((d.maturity ?? 0)/d.target)*100}%`}}/></div><b>{d.maturity ? `ML${d.maturity}` : "N/V"}</b></div>)}</div></Panel></div>
  <div className="two-col lower"><Panel title="Delivery portfolio" eyebrow="Cybersecurity projects"><div className="project-list">{projects.slice(0,6).map(p=><div key={p.name}><span className="project-icon"><BriefcaseBusiness size={16}/></span><div><strong>{p.name}</strong><small>{p.workstream} • {p.dependency}</small></div><Badge status={p.status}/></div>)}</div></Panel><Panel title="Assurance dependency" eyebrow="Critical path"><div className="dependency"><div><Network/><strong>Network<br/>segmentation</strong><Badge status="In Progress"/></div><ChevronRight/><div><Gauge/><strong>Vulnerability<br/>assessment</strong><Badge status="Planned"/></div><ChevronRight/><div><Shield/><strong>PT / Red Team</strong><Badge status="Blocked"/></div></div><div className="callout"><AlertTriangle size={18}/><p>Internal testing should follow sufficient segmentation and vulnerability assessment readiness.</p></div></Panel></div>
</> }

function Sama() { const metrics=[["Total controls",samaSummary.total],["Closed",samaSummary.closed],["In progress",samaSummary.inProgress],["Not started",samaSummary.notStarted],["Blocked",samaSummary.blocked],["N/A",samaSummary.notApplicable]]; return <><PageTitle eyebrow="Regulatory readiness" title="SAMA Cyber Security Framework" subtitle="Control status, maturity, gaps and evidence mapped in one workspace." badge="Target ML3"/><div className="metric-strip">{metrics.map(([a,b])=><div key={a as string}><span>{a}</span><strong><EmptyValue value={b}/></strong></div>)}</div>
  <div className="three-col"><Panel title="Control completion"><Donut data={[{name:"Unverified",value:237}]}/><div className="legend"><span><i className="gray-dot"/>Awaiting validated control totals</span></div></Panel><Panel title="Maturity by domain"><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={maturityDomains} layout="vertical" margin={{left:0,right:20}}><CartesianGrid stroke="#263247" horizontal={false}/><XAxis type="number" domain={[0,4]} stroke="#8190a8"/><YAxis dataKey="name" type="category" width={110} tick={{fontSize:11,fill:"#aab5c6"}}/><Tooltip contentStyle={{background:"#101827",border:"1px solid #25334a"}}/><Bar dataKey={(d)=>d.maturity||0} fill="#19c3a2" radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></div></Panel><Panel title="Evidence readiness"><Donut data={evidenceReadiness}/><div className="legend"><span><i className="teal-dot"/>Mapped demo items: 5</span><span><i className="gray-dot"/>Full mapping pending</span></div></Panel></div>
  <Panel title="Control register" eyebrow="Editable source: data/dashboard.ts" action={<button className="secondary">Export view</button>}><DataTable columns={["Control","Domain","Status","Owner","Due date","Gap / action"]} rows={controls.map(c=>[<strong key="id">{c.id}<small>{c.title}</small></strong>,c.domain,<Badge key="s" status={c.status}/>,c.owner,c.dueDate,<span key="g">{c.gap}<small>{c.remediation}</small></span>])}/></Panel><Panel title="Evidence tracker" eyebrow="One-to-many control mapping"><DataTable columns={["Evidence","Type","Status","Mapped controls","Owner","Last reviewed"]} rows={evidence.map(e=>[<strong key="e">{e.id}<small>{e.title}</small></strong>,e.type,<Badge key="s" status={e.status}/>,e.controlIds.join(", ")||"Unmapped",e.owner,e.lastReviewed])}/></Panel></> }

function Risks() { return <><PageTitle eyebrow="Enterprise cyber risk" title="Dynamic Risk Register" subtitle="Ratings are intentionally unassigned until approved by Muhlah risk owners." badge="9 themes tracked"/><div className="risk-banner"><ShieldAlert/><div><strong>No risk ratings have been fabricated.</strong><p>Likelihood, impact, inherent and residual ratings remain “Unrated” for authorised assessment.</p></div></div><div className="risk-layout"><Panel title="Risk matrix" eyebrow="Awaiting approved ratings"><div className="matrix"><div className="matrix-label y">IMPACT</div>{[5,4,3,2,1].map(y=>[1,2,3,4,5].map(x=><div key={`${x}-${y}`} className={`cell c${x+y}`}>{x===3&&y===3?<span>Place assessed<br/>risks here</span>:null}</div>))}<div className="matrix-label x">LIKELIHOOD</div></div></Panel><Panel title="Improvement themes"><div className="theme-list">{risks.map(r=><div key={r.id}><span>{r.id}</span><strong>{r.risk}</strong><Badge status={r.status}/></div>)}</div></Panel></div><Panel title="Risk register" action={<div className="filter-set"><button className="secondary">All status</button><button className="secondary">All owners</button></div>}><DataTable columns={["ID / Risk","Asset / process","Threat / vulnerability","Ratings","Treatment / owner","Target / status"]} rows={risks.map(r=>[<strong key="r">{r.id}<small>{r.risk}</small></strong>,r.asset,<span key="t">{r.threat}<small>{r.vulnerability}</small></span>,<span key="rt">Inherent: {r.inherent}<small>Residual: {r.residual}</small></span>,<span key="tr">{r.treatment}<small>{r.owner}</small></span>,<span key="st">{r.targetDate}<small><Badge status={r.status}/></small></span>])}/></Panel></> }

function Stack() { return <><PageTitle eyebrow="Security capabilities" title="Security Stack" subtitle="Operational tooling separated from implementation and planned capability." badge="10 solutions tracked"/><div className="solution-grid">{solutions.map(s=><article className="solution" key={s.name}><div className="solution-top"><span><Shield size={19}/></span><Badge status={s.status}/></div><h3>{s.name}</h3><p>{s.capability}</p><footer><small>{s.owner}</small><span>{s.note}</span></footer></article>)}</div><div className="two-col"><Panel title="Data classification" eyebrow="Microsoft sensitivity labels"><div className="classification">{["Top Secret","Secret","Confidential","Internal","Public"].map((x,i)=><div key={x}><span className={`class-dot d${i}`}/><strong>{x}</strong><small>Policy enforcement: Needs Verification</small></div>)}</div></Panel><Panel title="Procurement portfolio" eyebrow="Commercial amounts excluded"><div className="tag-cloud">{procurement.map(x=><span key={x}>{x}</span>)}</div></Panel></div></> }

function Infrastructure() { const stages=["Current state","Managed switching","VLAN design","Segmentation","Monitoring / NDR","Security validation","PT / Red Team"]; return <><PageTitle eyebrow="Infrastructure security" title="Modernisation & Cloud Assurance" subtitle="Improving internal boundaries, visibility and cloud control assurance." badge="Segmentation in progress"/><Panel title="Network modernisation path"><div className="roadmap horizontal">{stages.map((s,i)=><div key={s} className={i===0?"done":i===3?"active":""}><span>{i+1}</span><strong>{s}</strong><Badge status={i===0?"Needs Verification":i===3?"In Progress":i===6?"Blocked":"Planned"}/></div>)}</div></Panel><div className="three-col infra"><Panel title="Current / previous state"><ul><li>FortiGate and router</li><li>Two Ruijie unmanaged switches</li><li>Limited segmentation / historically single VLAN</li><li>~50 discoverable assets — verify</li></ul></Panel><Panel title="Target state"><ul><li>Managed Fortinet switches</li><li>Improved cabling and architecture</li><li>VLAN separation and stronger boundaries</li><li>Asset visibility and NDR monitoring</li></ul></Panel><Panel title="Identity & BYOD"><ul><li>Entra ID / Conditional Access</li><li>Intune where applicable</li><li>BlackBerry UEM and device enrolment</li><li>Compliant-device access direction</li></ul></Panel></div><div className="two-col"><Panel title="Stitch assurance focus" eyebrow="Fintech application technology"><div className="check-grid">{["Secure SDLC","Segregation of duties","Manual reviews","Audit logging","SIEM integration","Log retention","Access review","PAM","Disaster recovery","Security monitoring"].map(x=><span key={x}><BadgeCheck size={15}/>{x}</span>)}</div><div className="callout"><Cloud size={18}/><p>Google Cloud Saudi hosting/certification context and SOC 2 evidence should be validated in the vendor record.</p></div></Panel><Panel title="Oracle Cloud Infrastructure" eyebrow="Public-facing infrastructure"><div className="cloud-card"><Cloud/><div><strong>OCI security posture</strong><p>Load balancers, native cloud firewall capability and considered next-generation controls.</p></div></div><div className="stacked-status"><span>WAF status <Badge status="Gap"/></span><span>Logging / SIEM <Badge status="Needs Verification"/></span><span>Public IP review <Badge status="Needs Verification"/></span></div></Panel></div></> }

function ThirdParties() { return <><PageTitle eyebrow="Supply chain security" title="Third-Party Risk" subtitle="Risk-tiered assurance, contracts, resilience and regulatory applicability." badge="10 providers tracked"/><Panel title="Vendor portfolio"><DataTable columns={["Vendor / service","Criticality","Contract","Assessment","Assurance / regulatory","Owner / next review"]} rows={vendors.map(v=>[<strong key="v">{v.name}<small>{v.service}</small></strong>,v.criticality,<Badge key="c" status={v.contract}/>,<Badge key="a" status={v.assessment}/>,<span key="ar">{v.assurance}<small>{v.regulatory}</small></span>,<span key="o">{v.owner}<small>{v.nextReview}</small></span>])}/></Panel><Panel title="Excellent Solutions — outsourced call center" eyebrow="Control profile"><div className="control-chips">{["Muhlah-controlled devices","Restricted access","IPSec connectivity","MFA","Unique IDs","No unnecessary admin","No unauthorised RDP / VDI","PII / financial-data protection"].map(x=><span key={x}><ShieldCheck size={16}/>{x}</span>)}</div><div className="notice compact"><CircleHelp size={17}/>Control operation and evidence require periodic verification.</div></Panel></> }

function Resilience() { return <><PageTitle eyebrow="Business continuity" title="Cyber Resilience" subtitle="BIA, recovery objectives, vendor resilience and exercise evidence." badge="Maturity developing"/><div className="resilience-grid">{["Business Impact Analysis","Business Continuity Plan","Disaster Recovery","RTO / RPO","DR testing","Vendor DR","Cyber incident recovery","Estimated Time to Restore"].map((x,i)=><article key={x}><div><Siren size={18}/><Badge status={i<3?"In Progress":"Needs Verification"}/></div><strong>{x}</strong><p>Owner, scope, evidence and due date require validation.</p></article>)}</div><Panel title="Resilience lifecycle"><div className="dependency five"><div><strong>BIA</strong><Badge status="In Progress"/></div><ChevronRight/><div><strong>BCP</strong><Badge status="In Progress"/></div><ChevronRight/><div><strong>DR</strong><Badge status="In Progress"/></div><ChevronRight/><div><strong>Testing</strong><Badge status="Planned"/></div><ChevronRight/><div><strong>Improvement</strong><Badge status="Planned"/></div></div></Panel></> }

function People() { return <><PageTitle eyebrow="Workforce & culture" title="People, JML & Awareness" subtitle="Resource decisions, secure workforce lifecycle and professional capability." badge="Architecture role on hold"/><div className="three-col"><Panel title="Cybersecurity workforce"><div className="role-list">{[["Senior DFIR Specialist","Planned"],["SOC / DFIR L2 capability","Planned"],["Senior Cybersecurity Architect","On Hold"]].map(x=><div key={x[0]}><BriefcaseBusiness/><span><strong>{x[0]}</strong><small>Candidate / start date: Needs Verification</small></span><Badge status={x[1]}/></div>)}</div></Panel><Panel title="Awareness programme"><div className="awareness-number"><strong>—</strong><span>Completion rate<br/>Needs Verification</span></div><ul><li>KnowBe4 campaigns and phishing simulations</li><li>Mandatory and new-joiner awareness</li><li>Click, report and completion metrics</li><li>Saudi National Day fraud, QR and impersonation campaign</li></ul></Panel><Panel title="JML workflow"><div className="jml">{["HR","Dept. Head","CFO","IT","People","Compliance","Cybersecurity","Awareness","Asset"].map((x,i)=><span key={x}>{x}{i<8&&<ChevronRight/>}</span>)}</div><p className="muted-block">Track approvals, identity, email, UEM, Netskope, KnowBe4, SOC, business systems, device enrolment, revocation and asset recovery.</p></Panel></div><Panel title="Cybersecurity Leadership & Architecture Development" eyebrow="Professional development — no certification claimed"><div className="leadership-path"><div><GraduationCap/><strong>Cybersecurity<br/>Leadership</strong></div><ChevronRight/><div><Shield/><strong>Architecture<br/>Capability</strong></div><ChevronRight/><div className="courses"><span><b>SABSA</b><small>Security architecture • travel may be required</small><Badge status="Proposed"/></span><span><b>TOGAF</b><small>Enterprise architecture • regional / remote options</small><Badge status="Proposed"/></span></div><ChevronRight/><div><BookOpenCheck/><strong>Improved Internal<br/>Architecture Governance</strong></div></div></Panel></> }

function Roadmap() { return <><PageTitle eyebrow="Delivery sequencing" title="Cybersecurity Roadmap" subtitle="Dependencies and planned capability progression across seven workstreams." badge="Dates need verification"/><Panel title="Integrated roadmap"><div className="lane-list">{roadmap.map(l=><div className="lane" key={l.name}><strong>{l.name}</strong><div>{l.stages.map((s,i)=><span key={s.label}><em>{i+1}</em><b>{s.label}</b><Badge status={s.status}/>{i<l.stages.length-1&&<ChevronRight/>}</span>)}</div></div>)}</div></Panel><div className="two-col"><Panel title="SAMA progress over time" eyebrow="Illustrative values — replace with approved snapshots"><div className="chart tall"><ResponsiveContainer width="100%" height="100%"><AreaChart data={progressTrend}><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#19c3a2" stopOpacity={.35}/><stop offset="95%" stopColor="#19c3a2" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#263247"/><XAxis dataKey="period" stroke="#8794a8"/><YAxis stroke="#8794a8"/><Tooltip contentStyle={{background:"#101827",border:"1px solid #25334a"}}/><Area type="monotone" dataKey="value" stroke="#19c3a2" fill="url(#area)" strokeWidth={3}/></AreaChart></ResponsiveContainer></div></Panel><Panel title="Planning principles"><div className="principles"><p><span>01</span><strong>Sequence by dependency</strong><small>Infrastructure readiness before assurance testing.</small></p><p><span>02</span><strong>Evidence as delivery output</strong><small>Every completed activity produces traceable evidence.</small></p><p><span>03</span><strong>Executive decisions visible</strong><small>Approval, budget and risk decisions stay in the attention queue.</small></p></div></Panel></div></> }

function DataUpdates() { return <><PageTitle eyebrow="Maintainability" title="Data & Update Center" subtitle="All demo records are separated from UI components and ready for a future API." badge="Typed data layer"/><div className="data-cards"><article><FileCheck2/><strong>Primary data source</strong><code>/data/dashboard.ts</code><p>Edit validated values here. The UI recalculates and renders from typed records.</p></article><article><BadgeCheck/><strong>Data contracts</strong><code>/types/index.ts</code><p>Shared models keep status, ownership and evidence fields consistent.</p></article><article><Fingerprint/><strong>Authentication placeholder</strong><code>AUTH_PROVIDER / AUTH_SECRET</code><p>Production access must be private and identity-gated before deployment.</p></article></div><Panel title="Update procedure"><ol className="steps"><li><span>1</span><div><strong>Validate source</strong><p>Confirm owner, evidence and effective date.</p></div></li><li><span>2</span><div><strong>Update typed record</strong><p>Keep uncertainty as “Needs Verification” or “Unrated”.</p></div></li><li><span>3</span><div><strong>Review dashboard</strong><p>Check executive cards, detail tables and attention queue.</p></div></li><li><span>4</span><div><strong>Approve and commit</strong><p>Use a meaningful commit with reviewer traceability.</p></div></li></ol></Panel></> }

export default function Dashboard() {
  const [section,setSection]=useState<SectionId>("overview"); const [mobile,setMobile]=useState(false); const [query,setQuery]=useState("");
  const searchResults=useMemo(()=>query.trim().length<2?[]:[...risks.map(x=>({title:x.risk,meta:`Risk • ${x.status}`,section:"risks" as SectionId})),...controls.map(x=>({title:x.title,meta:`Control • ${x.status}`,section:"sama" as SectionId})),...solutions.map(x=>({title:x.name,meta:`Solution • ${x.status}`,section:"stack" as SectionId})),...vendors.map(x=>({title:x.name,meta:`Vendor • ${x.assessment}`,section:"third-parties" as SectionId}))].filter(x=>(x.title+x.meta).toLowerCase().includes(query.toLowerCase())).slice(0,6),[query]);
  const content={overview:<Overview onGo={setSection}/>,sama:<Sama/>,risks:<Risks/>,stack:<Stack/>,infrastructure:<Infrastructure/>,"third-parties":<ThirdParties/>,resilience:<Resilience/>,people:<People/>,roadmap:<Roadmap/>,data:<DataUpdates/>}[section];
  return <div className="shell"><aside className={mobile?"open":""}><div className="brand"><div>M</div><span><strong>MUHLAH</strong><small>CYBERSECURITY</small></span><button onClick={()=>setMobile(false)}><X/></button></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={section===id?"active":""} onClick={()=>{setSection(id);setMobile(false)}}><Icon size={18}/><span>{label}</span>{section===id&&<i/>}</button>)}</nav><div className="sidebar-foot"><ShieldCheck/><div><strong>CONFIDENTIAL</strong><small>Internal use only</small></div></div></aside><div className="main"><header><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search controls, risks, vendors…"/>{searchResults.length>0&&<div className="search-results">{searchResults.map((r,i)=><button key={i} onClick={()=>{setSection(r.section);setQuery("")}}><strong>{r.title}</strong><span>{r.meta}</span></button>)}</div>}</div><div className="header-meta"><span className="live-dot"/>Live reporting workspace<div className="avatar">CS</div></div></header><main>{content}</main><footer>CONFIDENTIAL – INTERNAL MUHLAH CYBERSECURITY USE ONLY <span>•</span> Placeholder data must be validated before reporting.</footer></div></div>;
}
